FROM --platform=linux/amd64 ghcr.io/tianocore/containers/ubuntu-22-dev:latest

RUN apt-get update \
  && apt-get install -y \
  autoconf \
  bison \
  cpio \
  dkms \
  flex \
  gawk \
  libelf-dev \
  libiberty-dev \
  libncurses-dev \
  libpci-dev \
  libssl-dev \
  libudev-dev \
  llvm \
  ninja-build \
  openssl \
  rsync \
  zstd
